name: SmpCore
version: '${project.version}'
main: me.karlito1501.smpcore.SmpCore
api-version: 1.18
authors: [ karlo292, 3au ]
website: karlito1501.xyz


commands:
  gmc:
    description: Changes gamemode of player to creative
    usage: /<command>
    aliases: creative

  gms:
    description: Changes gamemode of player to survival
    usage: /<command>
    aliases: survival

  gma:
    description: Changes gamemode of player to adventure
    usage: /<command>
    aliases: adventure

  gmsp:
    description: Changes gamemode of player to spectator
    usage: /<command>
    aliases: spectator

  day:
    description: Changes time to day
    usage: /<command>

  night:
    description: Changes time to night
    usage: /<command>

  tp:
    description: Teleports you to target player
    usage: /<command>